# --- STAGE 1: Build the Angular app ---
FROM node:24.13.0-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ARG BUILD_PROFILE=production
RUN npm run build -- --configuration=${BUILD_PROFILE}


# --- STAGE 2: Serve with Nginx ---
FROM nginx:alpine

COPY --from=build /app/dist/applyflow-ui /usr/share/nginx/html

# Copy your nginx.conf and entrypoint from the root context
COPY nginx.conf /etc/nginx/nginx.conf
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENV PORT=80
EXPOSE 80

ENTRYPOINT ["/entrypoint.sh"]